### PR TITLE
Prevent crash when selecting NULL-valued attributes

### LINKED ISSUE #145: Crash in CSS class selector when document contains empty class attributes
CSS class selectors crash if the document contains HTML tags with empty-values class attributes.
 
Background: I tried to parse a website that turned out to be a text file filled with URLs in angle brackets, of which one contains the word `class`. The file looks a little like this:
```
... Lots of stuff here ...

<http://experiment.worldcat.org/entity/work/data/2865052259#Person/cicero_marcus_tullius> <http://schema.org/name> "Marcus Tullius Cicero" .
<http://dewey.info/class/937.05092/e21/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Intangible> .
<http://experiment.worldcat.org/entity/work/data/2865052259#Topic/hommes_d_etat_rome> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Intangible> .
<http://experiment.worldcat.org/entity/work/data/2865052259#Topic/hommes_d_etat_rome> <http://schema.org/name> "Hommes d'État--Rome"@fr .

... Lots of more stuff here ...
```
This is not valid HTML, but it shouldn't crash. The crash happens because of this part:
```
<http://dewey.info/class/937.05092/e21/> 
```

The issue is reproducible also with valid HTML such as
```
<foo class>
```
No matter which class selector I use or whether it matches any element or not, I get a segfault with the following code:
```c
lxb_status_t css_cb(lxb_dom_node_t*, lxb_css_selector_specificity_t*, void*) {
    return LXB_STATUS_OK;
}

int main(void) {
    static const lxb_char_t html[] = "<http://dewey.info/class/937.05092/e21/> ";     // Crash
//    static const lxb_char_t html[] = "<foo class>";                                 // Crash
//    static const lxb_char_t html[] = "<foo class='bar'>";                           // Works

    lxb_html_document_t* html_document = lxb_html_document_create();
    lxb_html_document_parse(html_document, html, sizeof(html) - 1);
    lxb_dom_document_t* document = &html_document->dom_document;

    lxb_css_parser_t* css_parser = lxb_css_parser_create();
    lxb_css_parser_init(css_parser, NULL, NULL);

    lxb_css_selectors_t* css_selectors = lxb_css_selectors_create();
    lxb_css_selectors_init(css_selectors, 32);
    lxb_css_parser_selectors_set(css_parser, css_selectors);

    lxb_selectors_t* selectors = lxb_selectors_create();
    lxb_selectors_init(selectors);

    static const lxb_char_t selector[] = ".class-selector";
    lxb_css_selector_list_t* sel_list = lxb_css_selectors_parse(css_parser, selector, sizeof(selector) - 1);

    // SEGFAULT HERE
    lxb_selectors_find(selectors, lxb_dom_interface_node(document), sel_list, (lxb_selectors_cb_f)css_cb, NULL);

    return 0;
}
```

This may already be fixed with your CSS rework, but it is reproducible on the master branch at least.

### PR DESCRIPTION
**Pull request by phoerious**
There were multiple situations in which Lexbor would crash when a selected attribute had either no value or an empty value was given to the match function.

This PR prevents the following crashes:

- Matching of class names or attributes with `lxb_dom_elements_by_class_name()` or `lxb_dom_elements_by_attr()` when the document contains elements with `NULL`-valued attributes
- CSS class, ID, or attribute selectors when the document contains elements with `NULL`-valued attributes
- `lxb_dom_elements_by_class_name()` and `lxb_dom_elements_by_attr()` when given an empty (non-`NULL`, but zero-length) or `NULL` value for comparison

If you pass an empty/`NULL` value to `lxb_dom_elements_by_class_name()`, it won't match anything, but at least it doesn't crash anymore. `lxb_dom_elements_by_attr()` will match attributes with either empty or `NULL` values.

Fixes #145

Tests were added.

### CODE REVIEW

**Comment by phoerious** [comment]
For the time being, I created a custom manylinux Resiliparse build image from my own branch, which also includes the other unreleased fixes, so I can finally get rid of a few ugly workarounds and limitations.

https://github.com/chatnoir-eu/chatnoir-resiliparse/blob/develop/Dockerfile

**Comment by phoerious** [comment]
I processed, extracted, and indexed 24 million documents within the last hour, so far no crashes! :+1:

File: test/lexbor/html/element_by.c [hunk 1]
```diff
@@ -9,28 +9,35 @@
...
-                        "<div class='with-accordion      '>6</div>"
-                        "<div class='hidden    hidden  with-accordion'>7</div>"
-                        "<div class='with-accordion    hidden'>8</div>"
-                        "<div class='wewith-accordion'></div>"
-                        "<div class='with-accordionwe'></div>"
-                        "<div class='wewith-accordionwe'></div>"
-                        "<div class='with- accordion'></div>"
-                        "</body></html>";
-
     size_t len = sizeof(data) - 1;
```
Comment (lexborisov) [inline test/lexbor/html/element_by.c:41]: @phoerious 

This, apparently, should be made global as well.

```C
    static const size_t data_len = sizeof(data) - 1;
```

File: source/lexbor/dom/interfaces/element.c [hunk 2]
```diff
@@ -1095,63 +1096,63 @@ static bool
 lxb_dom_elements_by_attr_cmp_full(lxb_dom_element_cb_ctx_t *ctx,
                                   lxb_dom_attr_t *attr)
 {
-    if (ctx->value_length == attr->value->length
+    if (attr->value && ctx->value_length == attr->value->length
```
Comment (lexborisov) [inline source/lexbor/dom/interfaces/element.c:1099]: @phoerious 

```C
if (attr->value && 
```
replace
```C
if (attr->value != NULL && 
```

Only boolean variables are not checked for specific values.

**Comment by lexborisov** [comment]
@phoerious 

Thanks for the PR!
I started watching it. Tomorrow I will continue.
I need to check the behavior against the specification.

File: source/lexbor/dom/interfaces/element.c (hunk 2 above)
Comment (phoerious) [reply source/lexbor/dom/interfaces/element.c:1099]: I wasn't quite sure what you coding style here is. Usually, checking explicitly for == or != `NULL` is an antipattern and your code base wasn't entirely consistent either, but I'll change it.

**Comment by phoerious** [comment]
Changes made.

**Comment by lexborisov** [comment]
@phoerious 

Thanks for the patch, especially thanks for the added tests!
